// Generated by sprv/scripts/update-snapshot-model.mjs.
import { caseParticipants, participantAction } from '../case-students.js';
import { actionText, caseDescription } from '../case-options.js';
import { matchRosterStudent, receivedStudentContext } from './student-directory.js';

export const referencedForm = (row) => {
  const { receiverReference, ...form } = row.form;
  return row.reference ? { ...form, receiverReference: row.reference } : form;
};
export function studentCaseSummaries(form, studentId, students, grade) {
  if (form.kind === 'case') {
    const participants = caseParticipants(form).filter(
      (entry) => matchRosterStudent(entry, students, grade).student?.id === studentId,
    );
    return participants.map((entry) => {
      const action = participantAction(form, entry);
      return {
        date: form.date,
        type: form.type || '',
        description: caseDescription(form),
        action: actionText(action.action, action.actionState),
        due: form.due || '',
        status: form.status || '',
      };
    });
  }
  if (form.kind === 'cases')
    return (form.rows || [])
      .filter((entry) =>
        receivedStudentContext({ ...form, rows: [entry] }, students, grade).some(
          (match) => match.localStudent?.id === studentId,
        ),
      )
      .map((entry) => ({
        date: entry.date,
        type: entry.type || '',
        description: entry.description || '',
        action: actionText(entry.action, entry.actionState),
        due: entry.due || '',
        status: entry.status || '',
      }));
  return [];
}
